amplify-output:
  version: '1.1'
  auth:
    user_pool_id: 'us-west-2_DNf8QmZ93'
    aws_region: 'us-west-2'
    user_pool_client_id: 'rn8ngsijhd0rjuuogpvniuoku'
    identity_pool_id: 'us-west-2:1cc69010-296c-4250-a66b-41f7a82823ac'
    mfa_methods: []
    standard_required_attributes:
      - 'email'
      - 'given_name'
      - 'family_name'
    username_attributes:
      - 'email'
    user_verification_types:
      - 'email'
    mfa_configuration: 'NONE'
    password_policy:
      min_length: 8
      require_lowercase: true
      require_numbers: true
      require_symbols: true
      require_uppercase: true
    unauthenticated_identities_enabled: true

ssm_names: ['dk-local-websocket-url', 'dk-local-nats-token', 'dk-local-tls-certificate']

